server:
  port: 80
  servlet:
    context-path: /consumer2

eureka:
  #客户端注册进服务列表内
  client:
    register-with-eureka: false
    service-url:
      defaultZone: ${service.eureka02-url},${service.eureka02-url},${service.eureka03-url}

feign:
  hystrix:
    #启动hystrix
    enabled: true

#自定义参数
provider01:
  #此处必须有http，没有会报格式错误
#  url: http://127.0.0.1:8001/provider01
  url: http://PROVIDER/provider
  name: PROVIDER

service:
  eureka01-url: http://eureka7001:7001/eureka/
  eureka02-url: http://eureka7002:7002/eureka/
  eureka03-url: http://eureka7003:7003/eureka/