server:
  port: 58001

spring:
  application:
    name: test-01
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://222.2.2.2:3306/test_seata?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123654
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    alibaba:
      seata:
        # 这里要和 transaction service group mapping 的一致，并且与service端的也一致
        tx-service-group: my_test_tx_group

eureka:
  #客户端注册进服务列表内
  client:
    instance:
      instance-id: ${spring.application.name}
      #访问路径可以显示IP地址
      prefer-ip-address: true
    service-url:
      defaultZone: http://127.0.0.1:57001/eureka/

mybatis:
  type-aliases-package: com.jedreck.**.entitys
  mapper-locations: classpath:mapper/*.xml

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
