server:
  port: 8011
  servlet:
    context-path: /provider
spring:
  application:
    name: provider
eureka:
  #客户端注册进服务列表内
  client:
    instance:
      instance-id: provider-8011
      #访问路径可以显示IP地址
      prefer-ip-address: true
    service-url:
      defaultZone: ${service.eureka02-url},${service.eureka02-url},${service.eureka03-url}

#dashboard访问：http://127.0.0.1:8011/provider/actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

info:
  app.name: springcloud-experiment
  company.name: com.jedreck
  build.artifactId: @project.artifactId@
  build.version: @project.version@

#自定义信息
service:
  eureka01-url: http://eureka7001:7001/eureka/
  eureka02-url: http://eureka7002:7002/eureka/
  eureka03-url: http://eureka7003:7003/eureka/