server:
  port: 58005
spring:
  # redis 的配置
  redis:
    database: 2
    host: 222.2.2.2
    port: 6379
    timeout: 1000
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
