server:
  port: 7001
spring:
  application:
    name: eureka-7001
eureka:
  instance:
    # eureka服务端实例名称
    hostname: eureka01
  client:
    #不向注册中心注册自己
    register-with-eureka: false
    #自己端就是注册中心，职责是维护服务实例，不是检索服务
    fetch-registry: false
    service-url:
      #设置eureka server的交互地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://127.0.0.1:${server.port}/eureka/