server:
  port: 7001
spring:
  application:
    name: service-eureka

eureka:
  instance:
    # eureka服务端实例名称
    hostname: eureka7001
  client:
    #不向注册中心注册自己
    register-with-eureka: true
    #自己端就是注册中心，职责是维护服务实例，不是检索服务
    fetch-registry: false
    service-url:
      #设置eureka server的交互地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://127.0.0.1:${server.port}/eureka/
      defaultZone: ${service.eureka02-url},${service.eureka03-url}
  server:
    #自我保护,false-关闭
    enable-self-preservation: true

#自定义信息
service:
  eureka01-url: http://eureka7001:7001/eureka/
  eureka02-url: http://eureka7002:7002/eureka/
  eureka03-url: http://eureka7003:7003/eureka/