server:
  port: 8001
  servlet:
    context-path: /provider01
spring:
  application:
    name: provider-8001
eureka:
  #客户端注册进服务列表内
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
    instance:
      instance-id: provider-8001
      #访问路径可以显示IP地址
      prefer-ip-address: true
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$