server:
  port: 9527
  servlet:
    context-path: /zuul
spring:
  application:
    name: zuul-9527
eureka:
  #客户端注册进服务列表内
  client:
    instance:
      instance-id: zuul-9527
      #访问路径可以显示IP地址
      prefer-ip-address: true
    service-url:
      defaultZone: ${service.eureka02-url},${service.eureka02-url},${service.eureka03-url}

#zuul配置
zuul:
  routes:
    #这个可以将provider的路径，转移到/pro上，隐藏真实信息
    provide:
      serviceId: provider
      path: /pro/**
  #列出的服务将不能使用原url进行访问，或使用 "*"
  #ignored-services: provider
  ignored-services: "*"
  #同意前缀
  prefix: /jedreck

info:
  app.name: springcloud-experiment
  company.name: com.jedreck
  build.artifactId: @project.artifactId@
  build.version: @project.version@

#自定义信息
service:
  eureka01-url: http://eureka7001:7001/eureka/
  eureka02-url: http://eureka7002:7002/eureka/
  eureka03-url: http://eureka7003:7003/eureka/